name: Compile LaTeX

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install TeX Live
      run: sudo apt-get install texlive-full

    - name: Compile LaTeX
      run: pdflatex your_resume.tex && pdflatex main.tex
      # Replace 'your_resume.tex' with the name of your main LaTeX file
