name: Compile LaTeX

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install TeX Live
      run: sudo apt-get install texlive-full

    - name: Compile LaTeX
      run: |
        pdflatex main.tex
        pdflatex main.tex  # Run it twice to ensure proper references

    - name: Upload PDF
      uses: actions/upload-artifact@v2
      with:
        name: resume
        path: Software_Engineering_Resume.pdf  # This assumes your output PDF will be named main.pdf

